services:
  db:
    image: mysql:8.0
    container_name: football_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: futbol_db
      MYSQL_USER: futbol_user
      MYSQL_PASSWORD: futbol_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
  web:
    build: .
    container_name: football_analytics
    depends_on:
      db:
