services:
  db:
    image: mysql:8.0
    container_name: football_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: futbol_db
      MYSQL_USER: futbol_user
      MYSQL_PASSWORD: futbol_pass
